apiVersion: v1
kind: Namespace
metadata:
  name: mp3-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: mp3-server
  labels:
    app.kubernetes.io/name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
    spec:
      containers:
      - name: server
        image: server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: mp3-server
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
