apiVersion: v2
name: server-helm-chart
description: A Helm chart for the mp3-server application
version: 0.1.0
appVersion: "1.0"
icon: https://upload.wikimedia.org/wikipedia/en/9/97/Regis_University_logo.svg