name: C/C++ CI

on:
  push:
    paths:
      - client.c
      - server.c
      - Makefile

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
