name: C/C++ CI

on:
  push:
    paths:
      - *.c
      - Makefile
      - .github/workflows/c-cpp.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: make
      run: make
