name: C/C++ CI

on:
  push:
    paths:
      - '**/*.c'
      - Makefile
      - Dockerfile
      - .github/workflows/c-cpp.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpg123-dev libao-dev
    
    - name: Run make command
      run: make
      
    - name: Create SSL data
      run: openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.pem subj "/C=US/ST=CO/L=Denver/O=RegisUniversity/OU=CS469/CN=regis.edu/emailAddress=hsherwin@regis.edu"
      
    - name: Build server image
      run: |
        docker build -t server .
        docker images
      
    - name: Run a server container
      run: docker run -p 8080:8080 server
