name: C/C++ CI

on:
  push:
    paths-ignore:
      - '**/*.md'  # Ignore pushes that only change Markdown files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpg123-dev libao-dev
    
    - name: Run make command
      run: |
        make
      
    - name: Create SSL data
      run: openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.pem -subj "/C=US/ST=CO/L=Denver/O=RegisUniversity/OU=CS469/CN=regis.edu/emailAddress=hsherwin@regis.edu"
      
    - name: Build Docker image for server
      run: |
        docker build -t server .
        docker images
      
    - name: Run a server container
      run: docker run -d --name test-server -p 8080:8080 server
      
    - name: Check Docker container status
      run: |
        sleep 10  # Wait for the server to stabilize
        STATUS=$(docker inspect --format='{{.State.Status}}' test-server)
        if [ "$STATUS" != "running" ]; then
          echo "Server failed to start, status: $STATUS"
          exit 1
        else
          echo "Server is running, status: $STATUS"
        fi
    
    - name: Stop and remove Docker container
      run: |
        docker stop test-server
        docker rm test-server
        
    - name: Install Kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        
    - name: Start Minikube
      run: |
        minikube start --driver=docker --nodes=3 --insecure-registry="10.0.0.0/24"
        
    - name: Check Minikube and Cluster status (1)
      run: |
        sleep 10  # Wait for the nodes to stabilize
        minikube status
        kubectl get pods -A
        
    - name: Install Minikube Registry Addon
      run: |
        minikube addons enable registry
        
    - name: Get Minikube IP
      run: |
        echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV
    
    - name: Check Minikube registry status
      run: |
        kubectl get pods -n kube-system | grep registry
        kubectl get svc -n kube-system | grep registry
        
    - name: Port forward Minikube registry to localhost
      run: |
        kubectl port-forward --namespace kube-system svc/registry 5000:5000 &
        sleep 5  # Give it time to establish the port forwarding
        
    - name: Start Minikube tunnel for registry
      run: |
        sudo nohup minikube tunnel > /dev/null 2>&1 &

    
    - name: Configure Docker to allow insecure registry
      run: |
        echo '{
          "insecure-registries" : ["'${MINIKUBE_IP}':5000"]
        }' | sudo tee /etc/docker/daemon.json
        sudo systemctl daemon-reload
        sudo systemctl restart docker
    
    - name: Tag and push Docker image for server to Minikube registry
      run: |
        docker tag server:latest localhost:5000/server:latest
        docker push localhost:5000/server:latest
        docker images
    
    - name: Check Minikube and Cluster status (2)
      run: |
        minikube status
        kubectl get pods -A
    
    - name: Install Kubernetes Metrics Server
      run: |
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    
    - name: Replace Minikube IP in Kubernetes manifest
      run: |
        sed -i "s/\${MINIKUBE_IP}/${{ env.MINIKUBE_IP }}/g" k8s-manifest.yml
    
    - name: Apply Kubernetes manifest
      run: |
        kubectl apply -f k8s-manifest.yml
        
    - name: Check pod status and ensure all pods are running
      run: |
        echo "Checking if all pods are in Running state..."
        sleep 10  # Wait for the pods to stabilize
        kubectl get pods -A
        STATUS=$(kubectl get pods -n mp3-server --no-headers -o custom-columns=":status.phase")
        if echo "$STATUS" | grep -v "Running"; then
          echo "Some pods are not in Running state, failing the workflow."
          echo "Pod statuses: $STATUS"
          exit 1
        else
          echo "All pods are in Running state."
        fi

    - name: Check service status
      run: |
        echo "Checking service status..."
        kubectl get svc -n mp3-server
        minikube service server-service -n mp3-server --url
        
    - name: Check HorizontalPodAutoscaler (HPA) status
      run: |
        echo "Checking HPA status..."
        kubectl get hpa server-hpa -n mp3-server