name: Kubernetes Manifest Generation from Helm

on:
  push:
    paths:
      - 'server-helm-chart/**'
      - 'server-helm-chart/templates/**'
      - '.github/workflows/manifest-generation.yml'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        echo "Installing Helm..."
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Generate Kubernetes manifest
      run: |
        helm template server-release ./server-helm-chart > k8s-manifest-no-helm.yaml

    - name: Commit and push manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "harrison.sherwin@gmail.com"
        git config --global user.name "github-actions[bot]"
        git add k8s-manifest-no-helm.yaml
        git commit -m "Add generated Kubernetes manifest file"
        git push origin main
