name: Kubernetes Manifest Generation from Helm

on:
  push:
    paths:
      - 'server-helm-chart/**'
      - 'server-helm-chart/templates/**'
      - '.github/workflows/manifest-generation.yml'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        echo "Installing Helm..."
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Install kubeval
      run: |
        echo "Installing kubeval..."
        curl -sL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | tar xz
        sudo mv kubeval /usr/local/bin/

    
    - name: Generate Kubernetes manifest
      run: |
        echo "Generating Kubernetes manifest..."
        helm template server-release ./server-helm-chart > k8s-manifest-no-helm.yaml
        
    - name: Evaluate Kubernetes manifest with kubeval
      run: |
        echo "Evaluating Kubernetes manifest..."
        kubeval k8s-manifest-no-helm.yaml
        
    - name: Score Kubernetes manifest with kube-score
      run: |
        echo "Scoring Kubernetes manifest..."
        pwd
        docker run --rm -v "$(pwd):/ci" zegl/kube-score:latest score k8s-manifest-no-helm.yaml

    - name: Check for manifest changes compared to repo
      id: git_status
      run: |
        echo "Checking for Kubernetes manifest changes..."
        git add k8s-manifest-no-helm.yaml
        # Check if there are any changes
        if git diff --cached --quiet; then
          echo "No changes detected."
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Commit and push manifest
      if: env.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Pushing Kubernetes manifest changes..."
        git config --global user.email "harrison.sherwin@gmail.com"
        git config --global user.name "github-actions[bot]"
        # Commit and push the changes if any
        git commit -m "Update generated Kubernetes manifest file"
        git push origin main
