name: Kubernetes Manifest Generation from Helm

on:
  push:
    paths:
      - 'server-helm-chart/**'
      - 'server-helm-chart/templates/**'
      - '.github/workflows/manifest-generation.yml'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        echo "Installing Helm..."
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Generate Kubernetes manifest
      run: |
        helm template server-release ./server-helm-chart > k8s-manifest-no-helm.yaml

    - name: Check for changes
      id: git_status
      run: |
        git add k8s-manifest-no-helm.yaml
        # Check if there are any changes
        if git diff --cached --quiet; then
          echo "No changes detected."
          echo "changes_detected=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "changes_detected=true" >> $GITHUB_ENV
        fi

    - name: Commit and push manifest
      if: env.changes_detected == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "harrison.sherwin@gmail.com"
        git config --global user.name "github-actions[bot]"
        # Commit and push the changes if any
        git commit -m "Add generated Kubernetes manifest file"
        git push origin main
